In [1]:
# MRI STUFF
# Test increase in layers 
# Increase in layer architectures
# Increase in drop out 
# With class weights, without class weights 

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras.backend as K
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras import datasets, layers, models
from sklearn.metrics import (classification_report, confusion_matrix, balanced_accuracy_score, 
accuracy_score, roc_auc_score, auc)
from sklearn.model_selection import KFold, StratifiedKFold
import plotly.graph_objects as go
import glob

In [3]:
#drive.mount('/content/drive')

#ROOT_DIR = "/content/drive/MyDrive/Spring 2022/DTSC 870/Code" # HC Directory
#ROOT_DIR = "/content/drive/MyDrive/DTSC 870/Code" #MT Directory
KAGGLE_START = "/kaggle/input"
ROOT_DIR = KAGGLE_START
DATASET_01_TEST = KAGGLE_START + "/mri-test-set/test"
DATASET_01_TRAIN = KAGGLE_START + "/mri-trainset/train"
KAGGLE_OUT = "/kaggle/working"



In [4]:
datagen = ImageDataGenerator()
image_size = (256, 256)
test_set = datagen.flow_from_directory(DATASET_01_TEST, target_size=image_size, batch_size=32, class_mode='binary', shuffle=False)
train_set = datagen.flow_from_directory(DATASET_01_TRAIN, target_size=image_size, batch_size=32, class_mode='binary')


Found 121 images belonging to 2 classes.
Found 279 images belonging to 2 classes.


In [5]:
def create_model_V1():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(128, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model


In [6]:
def create_model_V1_02():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(128, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [7]:
def create_model_V1_04():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(128, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [8]:
def create_model_V2():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [9]:
def create_model_V2_02():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [10]:
def create_model_V2_04():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [11]:
def create_model_V3():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [12]:
def create_model_V3_02():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [13]:
def create_model_V3_04():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [14]:
#modify this 
norm_weight = 400/(2*(118+52))
tumor_weight = 400/(2*(161+69))

class_weights = {0:norm_weight, 1:tumor_weight}

In [15]:
import glob

#borrowed from svm code
def get_data_df(dir):
  # modified code from: https://www.kaggle.com/namgalielei/simple-load-images-and-count-number-of-each-class

  train_df = pd.DataFrame()

  trainset = glob.glob(dir)
  #print(trainset)
  train_df['filename'] = [img.split("/")[-4] + "/" + img.split("/")[-3] + "/" + img.split("/")[-2]+"/"+img.split("/")[-1] for img in trainset]
  train_df['label'] = [img.split("/")[-2] for img in trainset]

  return train_df

In [16]:
test_train = get_data_df(DATASET_01_TRAIN+"/*/*.jpg")
test_train.head()

filename  label
0   mri-trainset/train/Tumor/Tumor (77).jpg  Tumor
1  mri-trainset/train/Tumor/Tumor (116).jpg  Tumor
2   mri-trainset/train/Tumor/Tumor (86).jpg  Tumor
3   mri-trainset/train/Tumor/Tumor (49).jpg  Tumor
4   mri-trainset/train/Tumor/Tumor (40).jpg  Tumor

In [17]:
from sklearn.model_selection import KFold, StratifiedKFold

train_data = get_data_df(DATASET_01_TRAIN+"/*/*.jpg")
Y = train_data[['label']]

#Y = final_train[['label']]
#n = len(final_train)   

skf = StratifiedKFold(n_splits = 5, random_state = 7, shuffle = True) 

#Un needed preprocessing aside from rescale
idg = ImageDataGenerator(rescale=1./255)

#model name
def get_model_name(k):
    return 'model_'+str(k)+'.h5'
def model_test(fold_count, epoch, model_method, image_size):
  skf = StratifiedKFold(n_splits = fold_count, random_state = 7, shuffle = True)
  train_data = get_data_df(DATASET_01_TRAIN+"/*/*.jpg")
  Y = train_data[['label']]
  n = len (train_data)
  #Incorperate preprocessing in the method 
  #####################################################################
  #aug_train = get_data_df(DATASET_01_ROOT+"/Aug_train/*/*.jpg")
  #aug_train['filename'] = aug_train['filename'].str[7:]
  #final_train = test_train.append(aug_train, sort=False, ignore_index=True)


  #######################################################################
  idg = ImageDataGenerator(rescale=1./255)
  #idg = ImageDataGenerator()
  #Y = final_train[['label']]
  #n = len(final_train)    
  VALIDATION_ACCURACY = []
  VALIDATION_LOSS = []

  #create a directory
  save_dir = KAGGLE_OUT+'/datasets/01_MRI/Saved_CNN_Models/Testing/'+model_method.__name__+'/AugTest'+'/'+str(epoch)+'epochs/'
  img_dir = ROOT_DIR

  fold_var = 1

  #n is number of samples, doesn't care about x values for split, just y
  for train_index, val_index in skf.split(np.zeros(n),Y):

    #Index value for fold
    training_data = train_data.iloc[train_index]
    validation_data = train_data.iloc[val_index]
    #generator for train
    #print("hi")
    #Modify the training size, have an input adjustability 
    train_data_generator = idg.flow_from_dataframe(training_data, directory = img_dir,
                      target_size=image_size, batch_size=32,
                    x_col = "filename", y_col = "label",
                    class_mode = "binary", shuffle = True)
    #print("hi")
    #generator for validation
    valid_data_generator  = idg.flow_from_dataframe(validation_data, directory = img_dir,
                target_size=image_size, batch_size=32,
                x_col = "filename", y_col = "label",
                class_mode = "binary", shuffle = True)
    #print("hi")
    #create a method for this
    # CREATE NEW MODEL
    model = model_method()
    # COMPILE NEW MODEL
    #Binary cross entropy, opt will be adam, metric will be binary accuracy?
    model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
            optimizer= tf.keras.optimizers.Adam(),
            metrics=['binary_accuracy'])
    
    # CREATE CALLBACKS
    #Unsure about checpoint
    checkpoint = tf.keras.callbacks.ModelCheckpoint(save_dir+model_method.__name__+"_"+get_model_name(fold_var), 
                monitor='val_binary_accuracy', verbose=1, 
                save_best_only=True, mode='max')
  
    callbacks_list = [checkpoint]
    # There can be other callbacks, but just showing one because it involves the model name
    # This saves the best model
    # FIT THE MODEL
    #Include the weights for classes
    history = model.fit(train_data_generator,
            epochs=epoch,
            callbacks=callbacks_list,
            validation_data=valid_data_generator,
            class_weight = class_weights)
  
    #PLOT HISTORY
    #Plots for whichever
    #		:
    #plt.plot(history.history['binary_accuracy'], label='accuracy')
    #plt.plot(history.history['val_binary_accuracy'], label = 'val_accuracy')
    #plt.xlabel('Epoch')
    #plt.ylabel('Accuracy')
    #plt.ylim([0.3, 1])
    #plt.legend(loc='lower right')
    #plt.show()
    #frame = {'Accuracy': history.history['binary_accuracy'], 'Val_Accuracy': history.history['val_binary_accuracy']}
    #fig = px.line(frame)
    #fig.show()
    fig = go.Figure()
    fig.add_trace(go.Scatter(y= history.history['binary_accuracy'],
                      mode='lines+markers',
                      name='Training Accuracy'))
    fig.add_trace(go.Scatter(y= history.history['val_binary_accuracy'],
                      mode='lines+markers',
                      name='Validation Accuracy'))
    fig.update_yaxes(range=[0.40, 1])
    fig.update_layout(
      title="Fold "+ str(fold_var)+ "'s performance",
      title_x=0.5,
      xaxis_title="Epochs",
      yaxis_title="Accuracy",
      autosize=False,
      width=800,
      height=400,
      margin=dict(l=20, r=20, t=40, b=20),)
    fig.show()
    #		:
    # LOAD BEST MODEL to evaluate the performance of the model
    model.load_weights(save_dir+model_method.__name__+"_" + "model_"+str(fold_var)+".h5")
    predictions = model.predict(test_set)
    #predict_final = np.where(predictions >=0, 1,0)
    predict_final = K.round(predictions)
    conf_mat = confusion_matrix(test_set.classes, predict_final)
    conf_mat_perc = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
    class_acc = conf_mat_perc.diagonal()
    print(conf_mat)
    print()
    print(f"Normal accuracy: {class_acc[0]}")
    print(f"Tumor accuracy: {class_acc[1]}")
    print()
    target_names = ['Normal', 'Tumor']
    print(classification_report(test_set.classes, predict_final, target_names=target_names))
    print()
    w_acc = balanced_accuracy_score(test_set.classes, predict_final) 
    u_acc = accuracy_score(test_set.classes, predict_final)
    print(f'Unweighted Accuracy: {u_acc}')  
    print(f'Weighted Accuracy: {w_acc}')
    
    results = model.evaluate(test_set)
    results = dict(zip(model.metrics_names,results))
    
    VALIDATION_ACCURACY.append(results['binary_accuracy'])
    VALIDATION_LOSS.append(results['loss'])
    
    tf.keras.backend.clear_session()
    
    fold_var += 1

In [18]:
model_test(5, 30, create_model_V1, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.


2022-05-03 20:05:20.076044: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-03 20:05:20.155095: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-03 20:05:20.155940: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-03 20:05:20.157285: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compil

Epoch 1/30


2022-05-03 20:05:24.025835: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8005


7/7 [==============================] - 9s 230ms/step - loss: 5.6018 - binary_accuracy: 0.4843 - val_loss: 0.6660 - val_binary_accuracy: 0.5893

Epoch 00001: val_binary_accuracy improved from -inf to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V1/AugTest/30epochs/create_model_V1_model_1.h5
Epoch 2/30
7/7 [==============================] - 1s 146ms/step - loss: 0.6867 - binary_accuracy: 0.5471 - val_loss: 0.6511 - val_binary_accuracy: 0.5893

Epoch 00002: val_binary_accuracy did not improve from 0.58929
Epoch 3/30
7/7 [==============================] - 1s 134ms/step - loss: 0.6397 - binary_accuracy: 0.5964 - val_loss: 0.6144 - val_binary_accuracy: 0.5893

Epoch 00003: val_binary_accuracy did not improve from 0.58929
Epoch 4/30
7/7 [==============================] - 1s 136ms/step - loss: 0.5949 - binary_accuracy: 0.6861 - val_loss: 0.7045 - val_binary_accuracy: 0.5357

Epoch 00004: val_binary_accuracy did not improve from 0.58929
Epoch 5/

[[28 24]
 [ 9 60]]

Normal accuracy: 0.5384615384615384
Tumor accuracy: 0.8695652173913043

              precision    recall  f1-score   support

      Normal       0.76      0.54      0.63        52
       Tumor       0.71      0.87      0.78        69

    accuracy                           0.73       121
   macro avg       0.74      0.70      0.71       121
weighted avg       0.73      0.73      0.72       121


Unweighted Accuracy: 0.7272727272727273
Weighted Accuracy: 0.7040133779264214
4/4 [==============================] - 0s 105ms/step - loss: 143.1382 - binary_accuracy: 0.7273
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 174ms/step - loss: 3.3297 - binary_accuracy: 0.4888 - val_loss: 0.6626 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Tes

[[38 14]
 [17 52]]

Normal accuracy: 0.7307692307692307
Tumor accuracy: 0.7536231884057971

              precision    recall  f1-score   support

      Normal       0.69      0.73      0.71        52
       Tumor       0.79      0.75      0.77        69

    accuracy                           0.74       121
   macro avg       0.74      0.74      0.74       121
weighted avg       0.75      0.74      0.74       121


Unweighted Accuracy: 0.743801652892562
Weighted Accuracy: 0.7421962095875139
4/4 [==============================] - 0s 84ms/step - loss: 90.1204 - binary_accuracy: 0.7438
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 169ms/step - loss: 2.2701 - binary_accuracy: 0.5336 - val_loss: 0.6659 - val_binary_accuracy: 0.7679

Epoch 00001: val_binary_accuracy improved from -inf to 0.76786, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testin

[[34 18]
 [14 55]]

Normal accuracy: 0.6538461538461539
Tumor accuracy: 0.7971014492753623

              precision    recall  f1-score   support

      Normal       0.71      0.65      0.68        52
       Tumor       0.75      0.80      0.77        69

    accuracy                           0.74       121
   macro avg       0.73      0.73      0.73       121
weighted avg       0.73      0.74      0.73       121


Unweighted Accuracy: 0.7355371900826446
Weighted Accuracy: 0.725473801560758
4/4 [==============================] - 0s 86ms/step - loss: 86.8203 - binary_accuracy: 0.7355
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 161ms/step - loss: 3.0726 - binary_accuracy: 0.5022 - val_loss: 0.6812 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testin

[[31 21]
 [11 58]]

Normal accuracy: 0.5961538461538461
Tumor accuracy: 0.8405797101449275

              precision    recall  f1-score   support

      Normal       0.74      0.60      0.66        52
       Tumor       0.73      0.84      0.78        69

    accuracy                           0.74       121
   macro avg       0.74      0.72      0.72       121
weighted avg       0.74      0.74      0.73       121


Unweighted Accuracy: 0.7355371900826446
Weighted Accuracy: 0.7183667781493868
4/4 [==============================] - 0s 79ms/step - loss: 271.5840 - binary_accuracy: 0.7355
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 229ms/step - loss: 2.8561 - binary_accuracy: 0.4286 - val_loss: 0.6874 - val_binary_accuracy: 0.6727

Epoch 00001: val_binary_accuracy improved from -inf to 0.67273, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[31 21]
 [ 8 61]]

Normal accuracy: 0.5961538461538461
Tumor accuracy: 0.8840579710144928

              precision    recall  f1-score   support

      Normal       0.79      0.60      0.68        52
       Tumor       0.74      0.88      0.81        69

    accuracy                           0.76       121
   macro avg       0.77      0.74      0.74       121
weighted avg       0.77      0.76      0.75       121


Unweighted Accuracy: 0.7603305785123967
Weighted Accuracy: 0.7401059085841695
4/4 [==============================] - 0s 77ms/step - loss: 150.6412 - binary_accuracy: 0.7603


In [19]:
model_test(5, 30, create_model_V1_02, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 168ms/step - loss: 8.7048 - binary_accuracy: 0.5067 - val_loss: 0.7022 - val_binary_accuracy: 0.4107

Epoch 00001: val_binary_accuracy improved from -inf to 0.41071, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V1_02/AugTest/30epochs/create_model_V1_02_model_1.h5
Epoch 2/30
7/7 [==============================] - 1s 164ms/step - loss: 0.7013 - binary_accuracy: 0.4843 - val_loss: 0.6792 - val_binary_accuracy: 0.5893

Epoch 00002: val_binary_accuracy improved from 0.41071 to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V1_02/AugTest/30epochs/create_model_V1_02_model_1.h5
Epoch 3/30
7/7 [==============================] - 1s 135ms/step - loss: 0.6895 - binary_accuracy: 0.5740 - val_loss: 0.6738 - val_binary_accuracy: 0.5893

Epoch 0

[[32 20]
 [17 52]]

Normal accuracy: 0.6153846153846154
Tumor accuracy: 0.7536231884057971

              precision    recall  f1-score   support

      Normal       0.65      0.62      0.63        52
       Tumor       0.72      0.75      0.74        69

    accuracy                           0.69       121
   macro avg       0.69      0.68      0.69       121
weighted avg       0.69      0.69      0.69       121


Unweighted Accuracy: 0.6942148760330579
Weighted Accuracy: 0.6845039018952063
4/4 [==============================] - 1s 117ms/step - loss: 57.6038 - binary_accuracy: 0.6942
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 163ms/step - loss: 3.2664 - binary_accuracy: 0.5336 - val_loss: 0.6969 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[29 23]
 [ 7 62]]

Normal accuracy: 0.5576923076923077
Tumor accuracy: 0.8985507246376812

              precision    recall  f1-score   support

      Normal       0.81      0.56      0.66        52
       Tumor       0.73      0.90      0.81        69

    accuracy                           0.75       121
   macro avg       0.77      0.73      0.73       121
weighted avg       0.76      0.75      0.74       121


Unweighted Accuracy: 0.7520661157024794
Weighted Accuracy: 0.7281215161649944
4/4 [==============================] - 0s 85ms/step - loss: 234.5858 - binary_accuracy: 0.7521
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 174ms/step - loss: 6.3114 - binary_accuracy: 0.4664 - val_loss: 0.6810 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[36 16]
 [13 56]]

Normal accuracy: 0.6923076923076923
Tumor accuracy: 0.8115942028985508

              precision    recall  f1-score   support

      Normal       0.73      0.69      0.71        52
       Tumor       0.78      0.81      0.79        69

    accuracy                           0.76       121
   macro avg       0.76      0.75      0.75       121
weighted avg       0.76      0.76      0.76       121


Unweighted Accuracy: 0.7603305785123967
Weighted Accuracy: 0.7519509476031215
4/4 [==============================] - 0s 77ms/step - loss: 187.2400 - binary_accuracy: 0.7603
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 175ms/step - loss: 6.6393 - binary_accuracy: 0.4933 - val_loss: 0.7044 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[31 21]
 [11 58]]

Normal accuracy: 0.5961538461538461
Tumor accuracy: 0.8405797101449275

              precision    recall  f1-score   support

      Normal       0.74      0.60      0.66        52
       Tumor       0.73      0.84      0.78        69

    accuracy                           0.74       121
   macro avg       0.74      0.72      0.72       121
weighted avg       0.74      0.74      0.73       121


Unweighted Accuracy: 0.7355371900826446
Weighted Accuracy: 0.7183667781493868
4/4 [==============================] - 0s 89ms/step - loss: 383.8522 - binary_accuracy: 0.7355
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 180ms/step - loss: 8.8607 - binary_accuracy: 0.5045 - val_loss: 0.7329 - val_binary_accuracy: 0.4182

Epoch 00001: val_binary_accuracy improved from -inf to 0.41818, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[32 20]
 [15 54]]

Normal accuracy: 0.6153846153846154
Tumor accuracy: 0.782608695652174

              precision    recall  f1-score   support

      Normal       0.68      0.62      0.65        52
       Tumor       0.73      0.78      0.76        69

    accuracy                           0.71       121
   macro avg       0.71      0.70      0.70       121
weighted avg       0.71      0.71      0.71       121


Unweighted Accuracy: 0.7107438016528925
Weighted Accuracy: 0.6989966555183946
4/4 [==============================] - 0s 82ms/step - loss: 252.7120 - binary_accuracy: 0.7107


In [20]:
model_test(5, 30, create_model_V1_04, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 195ms/step - loss: 7.4381 - binary_accuracy: 0.5022 - val_loss: 0.6900 - val_binary_accuracy: 0.5893

Epoch 00001: val_binary_accuracy improved from -inf to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V1_04/AugTest/30epochs/create_model_V1_04_model_1.h5
Epoch 2/30
7/7 [==============================] - 1s 135ms/step - loss: 0.6927 - binary_accuracy: 0.5516 - val_loss: 0.6868 - val_binary_accuracy: 0.5893

Epoch 00002: val_binary_accuracy did not improve from 0.58929
Epoch 3/30
7/7 [==============================] - 1s 147ms/step - loss: 0.6873 - binary_accuracy: 0.5919 - val_loss: 0.6886 - val_binary_accuracy: 0.6429

Epoch 00003: val_binary_accuracy improved from 0.58929 to 0.64286, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_mode

[[35 17]
 [14 55]]

Normal accuracy: 0.6730769230769231
Tumor accuracy: 0.7971014492753623

              precision    recall  f1-score   support

      Normal       0.71      0.67      0.69        52
       Tumor       0.76      0.80      0.78        69

    accuracy                           0.74       121
   macro avg       0.74      0.74      0.74       121
weighted avg       0.74      0.74      0.74       121


Unweighted Accuracy: 0.743801652892562
Weighted Accuracy: 0.7350891861761427
4/4 [==============================] - 1s 131ms/step - loss: 430.2150 - binary_accuracy: 0.7438
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 186ms/step - loss: 6.7119 - binary_accuracy: 0.5561 - val_loss: 0.7150 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[33 19]
 [12 57]]

Normal accuracy: 0.6346153846153846
Tumor accuracy: 0.8260869565217391

              precision    recall  f1-score   support

      Normal       0.73      0.63      0.68        52
       Tumor       0.75      0.83      0.79        69

    accuracy                           0.74       121
   macro avg       0.74      0.73      0.73       121
weighted avg       0.74      0.74      0.74       121


Unweighted Accuracy: 0.743801652892562
Weighted Accuracy: 0.7303511705685619
4/4 [==============================] - 0s 92ms/step - loss: 313.0520 - binary_accuracy: 0.7438
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 175ms/step - loss: 3.0698 - binary_accuracy: 0.4574 - val_loss: 0.6930 - val_binary_accuracy: 0.5536

Epoch 00001: val_binary_accuracy improved from -inf to 0.55357, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[23 29]
 [ 6 63]]

Normal accuracy: 0.4423076923076923
Tumor accuracy: 0.9130434782608695

              precision    recall  f1-score   support

      Normal       0.79      0.44      0.57        52
       Tumor       0.68      0.91      0.78        69

    accuracy                           0.71       121
   macro avg       0.74      0.68      0.68       121
weighted avg       0.73      0.71      0.69       121


Unweighted Accuracy: 0.7107438016528925
Weighted Accuracy: 0.6776755852842808
4/4 [==============================] - 1s 129ms/step - loss: 307.0442 - binary_accuracy: 0.7107
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 214ms/step - loss: 8.3288 - binary_accuracy: 0.4709 - val_loss: 0.6971 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Tes

[[16 36]
 [ 4 65]]

Normal accuracy: 0.3076923076923077
Tumor accuracy: 0.9420289855072463

              precision    recall  f1-score   support

      Normal       0.80      0.31      0.44        52
       Tumor       0.64      0.94      0.76        69

    accuracy                           0.67       121
   macro avg       0.72      0.62      0.60       121
weighted avg       0.71      0.67      0.63       121


Unweighted Accuracy: 0.6694214876033058
Weighted Accuracy: 0.624860646599777
4/4 [==============================] - 0s 87ms/step - loss: 309.1507 - binary_accuracy: 0.6694
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 182ms/step - loss: 11.6984 - binary_accuracy: 0.4598 - val_loss: 0.7015 - val_binary_accuracy: 0.5818

Epoch 00001: val_binary_accuracy improved from -inf to 0.58182, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[30 22]
 [13 56]]

Normal accuracy: 0.5769230769230769
Tumor accuracy: 0.8115942028985508

              precision    recall  f1-score   support

      Normal       0.70      0.58      0.63        52
       Tumor       0.72      0.81      0.76        69

    accuracy                           0.71       121
   macro avg       0.71      0.69      0.70       121
weighted avg       0.71      0.71      0.71       121


Unweighted Accuracy: 0.7107438016528925
Weighted Accuracy: 0.6942586399108138
4/4 [==============================] - 1s 172ms/step - loss: 332.6908 - binary_accuracy: 0.7107


In [21]:
model_test(5, 30, create_model_V2, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 181ms/step - loss: 5.3111 - binary_accuracy: 0.4933 - val_loss: 1.2526 - val_binary_accuracy: 0.5893

Epoch 00001: val_binary_accuracy improved from -inf to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V2/AugTest/30epochs/create_model_V2_model_1.h5
Epoch 2/30
7/7 [==============================] - 1s 175ms/step - loss: 0.8305 - binary_accuracy: 0.5471 - val_loss: 0.6913 - val_binary_accuracy: 0.5179

Epoch 00002: val_binary_accuracy did not improve from 0.58929
Epoch 3/30
7/7 [==============================] - 1s 133ms/step - loss: 0.6008 - binary_accuracy: 0.7220 - val_loss: 0.5850 - val_binary_accuracy: 0.6607

Epoch 00003: val_binary_accuracy improved from 0.58929 to 0.66071, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V2/A

[[31 21]
 [ 9 60]]

Normal accuracy: 0.5961538461538461
Tumor accuracy: 0.8695652173913043

              precision    recall  f1-score   support

      Normal       0.78      0.60      0.67        52
       Tumor       0.74      0.87      0.80        69

    accuracy                           0.75       121
   macro avg       0.76      0.73      0.74       121
weighted avg       0.76      0.75      0.75       121


Unweighted Accuracy: 0.7520661157024794
Weighted Accuracy: 0.7328595317725752
4/4 [==============================] - 0s 80ms/step - loss: 188.6110 - binary_accuracy: 0.7521
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 276ms/step - loss: 7.3524 - binary_accuracy: 0.4753 - val_loss: 1.0774 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[33 19]
 [15 54]]

Normal accuracy: 0.6346153846153846
Tumor accuracy: 0.782608695652174

              precision    recall  f1-score   support

      Normal       0.69      0.63      0.66        52
       Tumor       0.74      0.78      0.76        69

    accuracy                           0.72       121
   macro avg       0.71      0.71      0.71       121
weighted avg       0.72      0.72      0.72       121


Unweighted Accuracy: 0.71900826446281
Weighted Accuracy: 0.7086120401337792
4/4 [==============================] - 0s 91ms/step - loss: 189.1699 - binary_accuracy: 0.7190
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 178ms/step - loss: 13.1074 - binary_accuracy: 0.5650 - val_loss: 2.9608 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testin

[[32 20]
 [16 53]]

Normal accuracy: 0.6153846153846154
Tumor accuracy: 0.7681159420289855

              precision    recall  f1-score   support

      Normal       0.67      0.62      0.64        52
       Tumor       0.73      0.77      0.75        69

    accuracy                           0.70       121
   macro avg       0.70      0.69      0.69       121
weighted avg       0.70      0.70      0.70       121


Unweighted Accuracy: 0.7024793388429752
Weighted Accuracy: 0.6917502787068004
4/4 [==============================] - 0s 81ms/step - loss: 134.1938 - binary_accuracy: 0.7025
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 172ms/step - loss: 5.8162 - binary_accuracy: 0.5247 - val_loss: 0.6628 - val_binary_accuracy: 0.7143

Epoch 00001: val_binary_accuracy improved from -inf to 0.71429, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[35 17]
 [14 55]]

Normal accuracy: 0.6730769230769231
Tumor accuracy: 0.7971014492753623

              precision    recall  f1-score   support

      Normal       0.71      0.67      0.69        52
       Tumor       0.76      0.80      0.78        69

    accuracy                           0.74       121
   macro avg       0.74      0.74      0.74       121
weighted avg       0.74      0.74      0.74       121


Unweighted Accuracy: 0.743801652892562
Weighted Accuracy: 0.7350891861761427
4/4 [==============================] - 0s 75ms/step - loss: 203.6855 - binary_accuracy: 0.7438
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 171ms/step - loss: 10.1153 - binary_accuracy: 0.5000 - val_loss: 2.9503 - val_binary_accuracy: 0.5818

Epoch 00001: val_binary_accuracy improved from -inf to 0.58182, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[30 22]
 [10 59]]

Normal accuracy: 0.5769230769230769
Tumor accuracy: 0.855072463768116

              precision    recall  f1-score   support

      Normal       0.75      0.58      0.65        52
       Tumor       0.73      0.86      0.79        69

    accuracy                           0.74       121
   macro avg       0.74      0.72      0.72       121
weighted avg       0.74      0.74      0.73       121


Unweighted Accuracy: 0.7355371900826446
Weighted Accuracy: 0.7159977703455964
4/4 [==============================] - 0s 91ms/step - loss: 221.7615 - binary_accuracy: 0.7355


In [22]:
model_test(5, 30, create_model_V2_02, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 183ms/step - loss: 13.6621 - binary_accuracy: 0.4843 - val_loss: 1.8517 - val_binary_accuracy: 0.5893

Epoch 00001: val_binary_accuracy improved from -inf to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V2_02/AugTest/30epochs/create_model_V2_02_model_1.h5
Epoch 2/30
7/7 [==============================] - 1s 136ms/step - loss: 1.3096 - binary_accuracy: 0.5740 - val_loss: 0.6876 - val_binary_accuracy: 0.5536

Epoch 00002: val_binary_accuracy did not improve from 0.58929
Epoch 3/30
7/7 [==============================] - 1s 146ms/step - loss: 0.6728 - binary_accuracy: 0.7175 - val_loss: 0.6933 - val_binary_accuracy: 0.4643

Epoch 00003: val_binary_accuracy did not improve from 0.58929
Epoch 4/30
7/7 [==============================] - 1s 151ms/step - loss: 0.6498 - binary_

[[36 16]
 [28 41]]

Normal accuracy: 0.6923076923076923
Tumor accuracy: 0.5942028985507246

              precision    recall  f1-score   support

      Normal       0.56      0.69      0.62        52
       Tumor       0.72      0.59      0.65        69

    accuracy                           0.64       121
   macro avg       0.64      0.64      0.64       121
weighted avg       0.65      0.64      0.64       121


Unweighted Accuracy: 0.6363636363636364
Weighted Accuracy: 0.6432552954292085
4/4 [==============================] - 0s 72ms/step - loss: 81.7221 - binary_accuracy: 0.6364
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 176ms/step - loss: 7.8779 - binary_accuracy: 0.4484 - val_loss: 0.6877 - val_binary_accuracy: 0.6071

Epoch 00001: val_binary_accuracy improved from -inf to 0.60714, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[27 25]
 [13 56]]

Normal accuracy: 0.5192307692307693
Tumor accuracy: 0.8115942028985508

              precision    recall  f1-score   support

      Normal       0.68      0.52      0.59        52
       Tumor       0.69      0.81      0.75        69

    accuracy                           0.69       121
   macro avg       0.68      0.67      0.67       121
weighted avg       0.68      0.69      0.68       121


Unweighted Accuracy: 0.6859504132231405
Weighted Accuracy: 0.66541248606466
4/4 [==============================] - 0s 81ms/step - loss: 106.8773 - binary_accuracy: 0.6860
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 174ms/step - loss: 5.1346 - binary_accuracy: 0.4484 - val_loss: 0.8290 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testin

[[29 23]
 [10 59]]

Normal accuracy: 0.5576923076923077
Tumor accuracy: 0.855072463768116

              precision    recall  f1-score   support

      Normal       0.74      0.56      0.64        52
       Tumor       0.72      0.86      0.78        69

    accuracy                           0.73       121
   macro avg       0.73      0.71      0.71       121
weighted avg       0.73      0.73      0.72       121


Unweighted Accuracy: 0.7272727272727273
Weighted Accuracy: 0.7063823857302118
4/4 [==============================] - 0s 92ms/step - loss: 181.1982 - binary_accuracy: 0.7273
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 181ms/step - loss: 8.4196 - binary_accuracy: 0.5426 - val_loss: 2.9200 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[33 19]
 [17 52]]

Normal accuracy: 0.6346153846153846
Tumor accuracy: 0.7536231884057971

              precision    recall  f1-score   support

      Normal       0.66      0.63      0.65        52
       Tumor       0.73      0.75      0.74        69

    accuracy                           0.70       121
   macro avg       0.70      0.69      0.69       121
weighted avg       0.70      0.70      0.70       121


Unweighted Accuracy: 0.7024793388429752
Weighted Accuracy: 0.6941192865105908
4/4 [==============================] - 0s 86ms/step - loss: 283.9409 - binary_accuracy: 0.7025
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 192ms/step - loss: 14.8527 - binary_accuracy: 0.5134 - val_loss: 1.0765 - val_binary_accuracy: 0.4182

Epoch 00001: val_binary_accuracy improved from -inf to 0.41818, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Tes

[[26 26]
 [ 9 60]]

Normal accuracy: 0.5
Tumor accuracy: 0.8695652173913043

              precision    recall  f1-score   support

      Normal       0.74      0.50      0.60        52
       Tumor       0.70      0.87      0.77        69

    accuracy                           0.71       121
   macro avg       0.72      0.68      0.69       121
weighted avg       0.72      0.71      0.70       121


Unweighted Accuracy: 0.7107438016528925
Weighted Accuracy: 0.6847826086956521
4/4 [==============================] - 0s 96ms/step - loss: 130.4181 - binary_accuracy: 0.7107


In [23]:
#model_test(5, 30, create_model_V2_04, (256,256))

In [24]:
#model_test(5, 30, create_model_V3, (256,256))

In [25]:
#model_test(5, 30, create_model_V3_02, (256,256))

In [26]:
#model_test(5, 30, create_model_V3_04, (256,256))