In [1]:
# MRI STUFF
# Test increase in layers 
# Increase in layer architectures
# Increase in drop out 
# With class weights, without class weights 

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras.backend as K
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras import datasets, layers, models
from sklearn.metrics import (classification_report, confusion_matrix, balanced_accuracy_score, 
accuracy_score, roc_auc_score, auc)
from sklearn.model_selection import KFold, StratifiedKFold
import plotly.graph_objects as go
import glob


In [3]:
#drive.mount('/content/drive')

#ROOT_DIR = "/content/drive/MyDrive/Spring 2022/DTSC 870/Code" # HC Directory
#ROOT_DIR = "/content/drive/MyDrive/DTSC 870/Code" #MT Directory
KAGGLE_START = "/kaggle/input"
ROOT_DIR = KAGGLE_START
DATASET_01_TEST = KAGGLE_START + "/mri-test-set/test"
DATASET_01_TRAIN = KAGGLE_START + "/mri-trainset/train"
KAGGLE_OUT = "/kaggle/working"



In [4]:
datagen = ImageDataGenerator()
image_size = (256, 256)
test_set = datagen.flow_from_directory(DATASET_01_TEST, target_size=image_size, batch_size=32, class_mode='binary', shuffle=False)
train_set = datagen.flow_from_directory(DATASET_01_TRAIN, target_size=image_size, batch_size=32, class_mode='binary')


Found 121 images belonging to 2 classes.
Found 279 images belonging to 2 classes.


In [5]:
def create_model_V1():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(128, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model


In [6]:
def create_model_V1_02():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(128, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [7]:
def create_model_V1_04():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(128, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [8]:
def create_model_V2():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [9]:
def create_model_V2_02():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [10]:
def create_model_V2_04():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [11]:
def create_model_V3():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [12]:
def create_model_V3_02():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [13]:
def create_model_V3_04():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [14]:
#modify this 
norm_weight = 400/(2*(118+52))
tumor_weight = 400/(2*(161+69))

class_weights = {0:norm_weight, 1:tumor_weight}

In [15]:
import glob

#borrowed from svm code
def get_data_df(dir):
  # modified code from: https://www.kaggle.com/namgalielei/simple-load-images-and-count-number-of-each-class

  train_df = pd.DataFrame()

  trainset = glob.glob(dir)
  #print(trainset)
  train_df['filename'] = [img.split("/")[-4] + "/" + img.split("/")[-3] + "/" + img.split("/")[-2]+"/"+img.split("/")[-1] for img in trainset]
  train_df['label'] = [img.split("/")[-2] for img in trainset]

  return train_df

In [16]:
test_train = get_data_df(DATASET_01_TRAIN+"/*/*.jpg")
test_train.head()

filename  label
0   mri-trainset/train/Tumor/Tumor (77).jpg  Tumor
1  mri-trainset/train/Tumor/Tumor (116).jpg  Tumor
2   mri-trainset/train/Tumor/Tumor (86).jpg  Tumor
3   mri-trainset/train/Tumor/Tumor (49).jpg  Tumor
4   mri-trainset/train/Tumor/Tumor (40).jpg  Tumor

In [17]:
from sklearn.model_selection import KFold, StratifiedKFold

train_data = get_data_df(DATASET_01_TRAIN+"/*/*.jpg")
Y = train_data[['label']]

#Y = final_train[['label']]
#n = len(final_train)   

skf = StratifiedKFold(n_splits = 5, random_state = 7, shuffle = True) 

#Un needed preprocessing aside from rescale
idg = ImageDataGenerator(rescale=1./255)

#model name
def get_model_name(k):
    return 'model_'+str(k)+'.h5'
def model_test(fold_count, epoch, model_method, image_size):
  skf = StratifiedKFold(n_splits = fold_count, random_state = 7, shuffle = True)
  train_data = get_data_df(DATASET_01_TRAIN+"/*/*.jpg")
  Y = train_data[['label']]
  n = len (train_data)
  #Incorperate preprocessing in the method 
  #####################################################################
  #aug_train = get_data_df(DATASET_01_ROOT+"/Aug_train/*/*.jpg")
  #aug_train['filename'] = aug_train['filename'].str[7:]
  #final_train = test_train.append(aug_train, sort=False, ignore_index=True)


  #######################################################################
  idg = ImageDataGenerator(rescale=1./255)
  #idg = ImageDataGenerator()
  #Y = final_train[['label']]
  #n = len(final_train)    
  VALIDATION_ACCURACY = []
  VALIDATION_LOSS = []

  #create a directory
  save_dir = KAGGLE_OUT+'/datasets/01_MRI/Saved_CNN_Models/Testing/'+model_method.__name__+'/AugTest'+'/'+str(epoch)+'epochs/'
  img_dir = ROOT_DIR

  fold_var = 1

  #n is number of samples, doesn't care about x values for split, just y
  for train_index, val_index in skf.split(np.zeros(n),Y):

    #Index value for fold
    training_data = train_data.iloc[train_index]
    validation_data = train_data.iloc[val_index]
    #generator for train
    #print("hi")
    #Modify the training size, have an input adjustability 
    train_data_generator = idg.flow_from_dataframe(training_data, directory = img_dir,
                      target_size=image_size, batch_size=32,
                    x_col = "filename", y_col = "label",
                    class_mode = "binary", shuffle = True)
    #print("hi")
    #generator for validation
    valid_data_generator  = idg.flow_from_dataframe(validation_data, directory = img_dir,
                target_size=image_size, batch_size=32,
                x_col = "filename", y_col = "label",
                class_mode = "binary", shuffle = True)
    #print("hi")
    #create a method for this
    # CREATE NEW MODEL
    model = model_method()
    # COMPILE NEW MODEL
    #Binary cross entropy, opt will be adam, metric will be binary accuracy?
    model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
            optimizer= tf.keras.optimizers.Adam(),
            metrics=['binary_accuracy'])
    
    # CREATE CALLBACKS
    #Unsure about checpoint
    checkpoint = tf.keras.callbacks.ModelCheckpoint(save_dir+model_method.__name__+"_"+get_model_name(fold_var), 
                monitor='val_binary_accuracy', verbose=1, 
                save_best_only=True, mode='max')
  
    callbacks_list = [checkpoint]
    # There can be other callbacks, but just showing one because it involves the model name
    # This saves the best model
    # FIT THE MODEL
    #Include the weights for classes
    history = model.fit(train_data_generator,
            epochs=epoch,
            callbacks=callbacks_list,
            validation_data=valid_data_generator,
            class_weight = class_weights)
  
    #PLOT HISTORY
    #Plots for whichever
    #		:
    #plt.plot(history.history['binary_accuracy'], label='accuracy')
    #plt.plot(history.history['val_binary_accuracy'], label = 'val_accuracy')
    #plt.xlabel('Epoch')
    #plt.ylabel('Accuracy')
    #plt.ylim([0.3, 1])
    #plt.legend(loc='lower right')
    #plt.show()
    #frame = {'Accuracy': history.history['binary_accuracy'], 'Val_Accuracy': history.history['val_binary_accuracy']}
    #fig = px.line(frame)
    #fig.show()
    fig = go.Figure()
    fig.add_trace(go.Scatter(y= history.history['binary_accuracy'],
                      mode='lines+markers',
                      name='Training Accuracy'))
    fig.add_trace(go.Scatter(y= history.history['val_binary_accuracy'],
                      mode='lines+markers',
                      name='Validation Accuracy'))
    fig.update_yaxes(range=[0.40, 1])
    fig.update_layout(
      title="Fold "+ str(fold_var)+ "'s performance",
      title_x=0.5,
      xaxis_title="Epochs",
      yaxis_title="Accuracy",
      autosize=False,
      width=800,
      height=400,
      margin=dict(l=20, r=20, t=40, b=20),)
    fig.show()
    #		:
    # LOAD BEST MODEL to evaluate the performance of the model
    model.load_weights(save_dir+model_method.__name__+"_" + "model_"+str(fold_var)+".h5")
    predictions = model.predict(test_set)
    #predict_final = np.where(predictions >=0, 1,0)
    predict_final = K.round(predictions)
    conf_mat = confusion_matrix(test_set.classes, predict_final)
    conf_mat_perc = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
    class_acc = conf_mat_perc.diagonal()
    print(conf_mat)
    print()
    print(f"Normal accuracy: {class_acc[0]}")
    print(f"Tumor accuracy: {class_acc[1]}")
    print()
    target_names = ['Normal', 'Tumor']
    print(classification_report(test_set.classes, predict_final, target_names=target_names))
    print()
    w_acc = balanced_accuracy_score(test_set.classes, predict_final) 
    u_acc = accuracy_score(test_set.classes, predict_final)
    print(f'Unweighted Accuracy: {u_acc}')  
    print(f'Weighted Accuracy: {w_acc}')
    results = model.evaluate(test_set)
    
    results = dict(zip(model.metrics_names,results))
    
    VALIDATION_ACCURACY.append(results['binary_accuracy'])
    VALIDATION_LOSS.append(results['loss'])
    
    tf.keras.backend.clear_session()
    
    fold_var += 1

In [18]:
#model_test(5, 30, create_model_V1, (256,256))

In [19]:
#model_test(5, 30, create_model_V1_02, (256,256))

In [20]:
#model_test(5, 30, create_model_V1_04, (256,256))

In [21]:
#model_test(5, 30, create_model_V2, (256,256))

In [22]:
#model_test(5, 30, create_model_V2_02, (256,256))

In [23]:
model_test(5, 30, create_model_V2_04, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.


2022-05-03 20:34:23.347239: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-03 20:34:23.454964: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-03 20:34:23.455723: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-05-03 20:34:23.456882: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compil

Epoch 1/30


2022-05-03 20:34:27.411645: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8005


7/7 [==============================] - 8s 265ms/step - loss: 14.9997 - binary_accuracy: 0.5291 - val_loss: 1.3682 - val_binary_accuracy: 0.4107

Epoch 00001: val_binary_accuracy improved from -inf to 0.41071, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V2_04/AugTest/30epochs/create_model_V2_04_model_1.h5
Epoch 2/30
7/7 [==============================] - 1s 132ms/step - loss: 1.3802 - binary_accuracy: 0.4260 - val_loss: 0.6933 - val_binary_accuracy: 0.5357

Epoch 00002: val_binary_accuracy improved from 0.41071 to 0.53571, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V2_04/AugTest/30epochs/create_model_V2_04_model_1.h5
Epoch 3/30
7/7 [==============================] - 1s 200ms/step - loss: 0.6856 - binary_accuracy: 0.5964 - val_loss: 0.6929 - val_binary_accuracy: 0.5893

Epoch 00003: val_binary_accuracy improved from 0.53571 to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[28 24]
 [ 8 61]]

Normal accuracy: 0.5384615384615384
Tumor accuracy: 0.8840579710144928

              precision    recall  f1-score   support

      Normal       0.78      0.54      0.64        52
       Tumor       0.72      0.88      0.79        69

    accuracy                           0.74       121
   macro avg       0.75      0.71      0.71       121
weighted avg       0.74      0.74      0.73       121


Unweighted Accuracy: 0.7355371900826446
Weighted Accuracy: 0.7112597547380156
4/4 [==============================] - 0s 85ms/step - loss: 193.9013 - binary_accuracy: 0.7355
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 173ms/step - loss: 19.0060 - binary_accuracy: 0.5874 - val_loss: 1.0841 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Tes

[[36 16]
 [25 44]]

Normal accuracy: 0.6923076923076923
Tumor accuracy: 0.6376811594202898

              precision    recall  f1-score   support

      Normal       0.59      0.69      0.64        52
       Tumor       0.73      0.64      0.68        69

    accuracy                           0.66       121
   macro avg       0.66      0.66      0.66       121
weighted avg       0.67      0.66      0.66       121


Unweighted Accuracy: 0.6611570247933884
Weighted Accuracy: 0.664994425863991
4/4 [==============================] - 0s 81ms/step - loss: 100.2499 - binary_accuracy: 0.6612
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 162ms/step - loss: 7.0430 - binary_accuracy: 0.4709 - val_loss: 2.4788 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[34 18]
 [13 56]]

Normal accuracy: 0.6538461538461539
Tumor accuracy: 0.8115942028985508

              precision    recall  f1-score   support

      Normal       0.72      0.65      0.69        52
       Tumor       0.76      0.81      0.78        69

    accuracy                           0.74       121
   macro avg       0.74      0.73      0.74       121
weighted avg       0.74      0.74      0.74       121


Unweighted Accuracy: 0.743801652892562
Weighted Accuracy: 0.7327201783723523
4/4 [==============================] - 0s 85ms/step - loss: 128.2908 - binary_accuracy: 0.7438
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 179ms/step - loss: 11.0923 - binary_accuracy: 0.5381 - val_loss: 1.0044 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[35 17]
 [16 53]]

Normal accuracy: 0.6730769230769231
Tumor accuracy: 0.7681159420289855

              precision    recall  f1-score   support

      Normal       0.69      0.67      0.68        52
       Tumor       0.76      0.77      0.76        69

    accuracy                           0.73       121
   macro avg       0.72      0.72      0.72       121
weighted avg       0.73      0.73      0.73       121


Unweighted Accuracy: 0.7272727272727273
Weighted Accuracy: 0.7205964325529544
4/4 [==============================] - 0s 88ms/step - loss: 303.2027 - binary_accuracy: 0.7273
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 193ms/step - loss: 14.6958 - binary_accuracy: 0.4688 - val_loss: 1.3769 - val_binary_accuracy: 0.4182

Epoch 00001: val_binary_accuracy improved from -inf to 0.41818, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Tes

[[34 18]
 [19 50]]

Normal accuracy: 0.6538461538461539
Tumor accuracy: 0.7246376811594203

              precision    recall  f1-score   support

      Normal       0.64      0.65      0.65        52
       Tumor       0.74      0.72      0.73        69

    accuracy                           0.69       121
   macro avg       0.69      0.69      0.69       121
weighted avg       0.69      0.69      0.69       121


Unweighted Accuracy: 0.6942148760330579
Weighted Accuracy: 0.6892419175027871
4/4 [==============================] - 0s 102ms/step - loss: 217.0323 - binary_accuracy: 0.6942


In [24]:
model_test(5, 30, create_model_V3, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 166ms/step - loss: 1.8780 - binary_accuracy: 0.4574 - val_loss: 0.6884 - val_binary_accuracy: 0.5893

Epoch 00001: val_binary_accuracy improved from -inf to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V3/AugTest/30epochs/create_model_V3_model_1.h5
Epoch 2/30
7/7 [==============================] - 1s 137ms/step - loss: 0.6897 - binary_accuracy: 0.6323 - val_loss: 0.7426 - val_binary_accuracy: 0.4107

Epoch 00002: val_binary_accuracy did not improve from 0.58929
Epoch 3/30
7/7 [==============================] - 1s 144ms/step - loss: 0.6560 - binary_accuracy: 0.6233 - val_loss: 0.5772 - val_binary_accuracy: 0.6429

Epoch 00003: val_binary_accuracy improved from 0.58929 to 0.64286, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V3/A

[[38 14]
 [16 53]]

Normal accuracy: 0.7307692307692307
Tumor accuracy: 0.7681159420289855

              precision    recall  f1-score   support

      Normal       0.70      0.73      0.72        52
       Tumor       0.79      0.77      0.78        69

    accuracy                           0.75       121
   macro avg       0.75      0.75      0.75       121
weighted avg       0.75      0.75      0.75       121


Unweighted Accuracy: 0.7520661157024794
Weighted Accuracy: 0.7494425863991081
4/4 [==============================] - 0s 101ms/step - loss: 149.3459 - binary_accuracy: 0.7521
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 162ms/step - loss: 1.7781 - binary_accuracy: 0.4798 - val_loss: 0.6830 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Tes

[[31 21]
 [ 5 64]]

Normal accuracy: 0.5961538461538461
Tumor accuracy: 0.927536231884058

              precision    recall  f1-score   support

      Normal       0.86      0.60      0.70        52
       Tumor       0.75      0.93      0.83        69

    accuracy                           0.79       121
   macro avg       0.81      0.76      0.77       121
weighted avg       0.80      0.79      0.78       121


Unweighted Accuracy: 0.7851239669421488
Weighted Accuracy: 0.7618450390189521
4/4 [==============================] - 0s 88ms/step - loss: 203.7980 - binary_accuracy: 0.7851
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 169ms/step - loss: 3.5002 - binary_accuracy: 0.6009 - val_loss: 0.6757 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[41 11]
 [11 58]]

Normal accuracy: 0.7884615384615384
Tumor accuracy: 0.8405797101449275

              precision    recall  f1-score   support

      Normal       0.79      0.79      0.79        52
       Tumor       0.84      0.84      0.84        69

    accuracy                           0.82       121
   macro avg       0.81      0.81      0.81       121
weighted avg       0.82      0.82      0.82       121


Unweighted Accuracy: 0.8181818181818182
Weighted Accuracy: 0.814520624303233
4/4 [==============================] - 0s 83ms/step - loss: 107.2178 - binary_accuracy: 0.8182
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 204ms/step - loss: 1.6451 - binary_accuracy: 0.5022 - val_loss: 0.7083 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[38 14]
 [13 56]]

Normal accuracy: 0.7307692307692307
Tumor accuracy: 0.8115942028985508

              precision    recall  f1-score   support

      Normal       0.75      0.73      0.74        52
       Tumor       0.80      0.81      0.81        69

    accuracy                           0.78       121
   macro avg       0.77      0.77      0.77       121
weighted avg       0.78      0.78      0.78       121


Unweighted Accuracy: 0.7768595041322314
Weighted Accuracy: 0.7711817168338908
4/4 [==============================] - 0s 79ms/step - loss: 307.8407 - binary_accuracy: 0.7769
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 184ms/step - loss: 1.8301 - binary_accuracy: 0.5759 - val_loss: 0.6720 - val_binary_accuracy: 0.5818

Epoch 00001: val_binary_accuracy improved from -inf to 0.58182, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[27 25]
 [ 6 63]]

Normal accuracy: 0.5192307692307693
Tumor accuracy: 0.9130434782608695

              precision    recall  f1-score   support

      Normal       0.82      0.52      0.64        52
       Tumor       0.72      0.91      0.80        69

    accuracy                           0.74       121
   macro avg       0.77      0.72      0.72       121
weighted avg       0.76      0.74      0.73       121


Unweighted Accuracy: 0.743801652892562
Weighted Accuracy: 0.7161371237458194
4/4 [==============================] - 0s 86ms/step - loss: 183.9213 - binary_accuracy: 0.7438


In [25]:
model_test(5, 30, create_model_V3_02, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 228ms/step - loss: 1.7520 - binary_accuracy: 0.4843 - val_loss: 0.6815 - val_binary_accuracy: 0.5893

Epoch 00001: val_binary_accuracy improved from -inf to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V3_02/AugTest/30epochs/create_model_V3_02_model_1.h5
Epoch 2/30
7/7 [==============================] - 1s 130ms/step - loss: 0.6910 - binary_accuracy: 0.5740 - val_loss: 0.6922 - val_binary_accuracy: 0.5893

Epoch 00002: val_binary_accuracy did not improve from 0.58929
Epoch 3/30
7/7 [==============================] - 1s 126ms/step - loss: 0.6935 - binary_accuracy: 0.5471 - val_loss: 0.6897 - val_binary_accuracy: 0.5893

Epoch 00003: val_binary_accuracy did not improve from 0.58929
Epoch 4/30
7/7 [==============================] - 1s 130ms/step - loss: 0.6863 - binary_a

[[40 12]
 [15 54]]

Normal accuracy: 0.7692307692307693
Tumor accuracy: 0.782608695652174

              precision    recall  f1-score   support

      Normal       0.73      0.77      0.75        52
       Tumor       0.82      0.78      0.80        69

    accuracy                           0.78       121
   macro avg       0.77      0.78      0.77       121
weighted avg       0.78      0.78      0.78       121


Unweighted Accuracy: 0.7768595041322314
Weighted Accuracy: 0.7759197324414716
4/4 [==============================] - 0s 75ms/step - loss: 110.5537 - binary_accuracy: 0.7769
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 175ms/step - loss: 1.4356 - binary_accuracy: 0.5202 - val_loss: 0.6922 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[42 10]
 [18 51]]

Normal accuracy: 0.8076923076923077
Tumor accuracy: 0.7391304347826086

              precision    recall  f1-score   support

      Normal       0.70      0.81      0.75        52
       Tumor       0.84      0.74      0.78        69

    accuracy                           0.77       121
   macro avg       0.77      0.77      0.77       121
weighted avg       0.78      0.77      0.77       121


Unweighted Accuracy: 0.768595041322314
Weighted Accuracy: 0.7734113712374582
4/4 [==============================] - 0s 109ms/step - loss: 144.6552 - binary_accuracy: 0.7686
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 158ms/step - loss: 5.3394 - binary_accuracy: 0.5291 - val_loss: 0.6908 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[33 19]
 [23 46]]

Normal accuracy: 0.6346153846153846
Tumor accuracy: 0.6666666666666666

              precision    recall  f1-score   support

      Normal       0.59      0.63      0.61        52
       Tumor       0.71      0.67      0.69        69

    accuracy                           0.65       121
   macro avg       0.65      0.65      0.65       121
weighted avg       0.66      0.65      0.65       121


Unweighted Accuracy: 0.6528925619834711
Weighted Accuracy: 0.6506410256410255
4/4 [==============================] - 0s 85ms/step - loss: 108.1253 - binary_accuracy: 0.6529
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 172ms/step - loss: 1.9230 - binary_accuracy: 0.4574 - val_loss: 0.6910 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[31 21]
 [12 57]]

Normal accuracy: 0.5961538461538461
Tumor accuracy: 0.8260869565217391

              precision    recall  f1-score   support

      Normal       0.72      0.60      0.65        52
       Tumor       0.73      0.83      0.78        69

    accuracy                           0.73       121
   macro avg       0.73      0.71      0.71       121
weighted avg       0.73      0.73      0.72       121


Unweighted Accuracy: 0.7272727272727273
Weighted Accuracy: 0.7111204013377926
4/4 [==============================] - 0s 83ms/step - loss: 290.2912 - binary_accuracy: 0.7273
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 201ms/step - loss: 3.6087 - binary_accuracy: 0.4866 - val_loss: 0.6890 - val_binary_accuracy: 0.5818

Epoch 00001: val_binary_accuracy improved from -inf to 0.58182, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[29 23]
 [16 53]]

Normal accuracy: 0.5576923076923077
Tumor accuracy: 0.7681159420289855

              precision    recall  f1-score   support

      Normal       0.64      0.56      0.60        52
       Tumor       0.70      0.77      0.73        69

    accuracy                           0.68       121
   macro avg       0.67      0.66      0.66       121
weighted avg       0.67      0.68      0.67       121


Unweighted Accuracy: 0.6776859504132231
Weighted Accuracy: 0.6629041248606466
4/4 [==============================] - 0s 82ms/step - loss: 43.5459 - binary_accuracy: 0.6777


In [26]:
model_test(5, 30, create_model_V3_04, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 172ms/step - loss: 6.6319 - binary_accuracy: 0.4753 - val_loss: 0.6935 - val_binary_accuracy: 0.4107

Epoch 00001: val_binary_accuracy improved from -inf to 0.41071, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V3_04/AugTest/30epochs/create_model_V3_04_model_1.h5
Epoch 2/30
7/7 [==============================] - 1s 132ms/step - loss: 0.6958 - binary_accuracy: 0.4215 - val_loss: 0.6928 - val_binary_accuracy: 0.5893

Epoch 00002: val_binary_accuracy improved from 0.41071 to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V3_04/AugTest/30epochs/create_model_V3_04_model_1.h5
Epoch 3/30
7/7 [==============================] - 1s 139ms/step - loss: 0.6934 - binary_accuracy: 0.5740 - val_loss: 0.6928 - val_binary_accuracy: 0.5893

Epoch 0

[[20 32]
 [12 57]]

Normal accuracy: 0.38461538461538464
Tumor accuracy: 0.8260869565217391

              precision    recall  f1-score   support

      Normal       0.62      0.38      0.48        52
       Tumor       0.64      0.83      0.72        69

    accuracy                           0.64       121
   macro avg       0.63      0.61      0.60       121
weighted avg       0.63      0.64      0.62       121


Unweighted Accuracy: 0.6363636363636364
Weighted Accuracy: 0.6053511705685619
4/4 [==============================] - 0s 76ms/step - loss: 39.9621 - binary_accuracy: 0.6364
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 161ms/step - loss: 5.8911 - binary_accuracy: 0.4709 - val_loss: 0.6932 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[30 22]
 [14 55]]

Normal accuracy: 0.5769230769230769
Tumor accuracy: 0.7971014492753623

              precision    recall  f1-score   support

      Normal       0.68      0.58      0.62        52
       Tumor       0.71      0.80      0.75        69

    accuracy                           0.70       121
   macro avg       0.70      0.69      0.69       121
weighted avg       0.70      0.70      0.70       121


Unweighted Accuracy: 0.7024793388429752
Weighted Accuracy: 0.6870122630992196
4/4 [==============================] - 0s 80ms/step - loss: 121.2107 - binary_accuracy: 0.7025
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 158ms/step - loss: 5.3852 - binary_accuracy: 0.5650 - val_loss: 0.6934 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Test

[[35 17]
 [19 50]]

Normal accuracy: 0.6730769230769231
Tumor accuracy: 0.7246376811594203

              precision    recall  f1-score   support

      Normal       0.65      0.67      0.66        52
       Tumor       0.75      0.72      0.74        69

    accuracy                           0.70       121
   macro avg       0.70      0.70      0.70       121
weighted avg       0.70      0.70      0.70       121


Unweighted Accuracy: 0.7024793388429752
Weighted Accuracy: 0.6988573021181717
4/4 [==============================] - 0s 83ms/step - loss: 64.3226 - binary_accuracy: 0.7025
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 168ms/step - loss: 2.8932 - binary_accuracy: 0.6054 - val_loss: 0.6938 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[24 28]
 [12 57]]

Normal accuracy: 0.46153846153846156
Tumor accuracy: 0.8260869565217391

              precision    recall  f1-score   support

      Normal       0.67      0.46      0.55        52
       Tumor       0.67      0.83      0.74        69

    accuracy                           0.67       121
   macro avg       0.67      0.64      0.64       121
weighted avg       0.67      0.67      0.66       121


Unweighted Accuracy: 0.6694214876033058
Weighted Accuracy: 0.6438127090301003
4/4 [==============================] - 0s 88ms/step - loss: 111.4538 - binary_accuracy: 0.6694
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 2s 169ms/step - loss: 3.0461 - binary_accuracy: 0.4688 - val_loss: 0.6927 - val_binary_accuracy: 0.5818

Epoch 00001: val_binary_accuracy improved from -inf to 0.58182, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Tes

[[24 28]
 [15 54]]

Normal accuracy: 0.46153846153846156
Tumor accuracy: 0.782608695652174

              precision    recall  f1-score   support

      Normal       0.62      0.46      0.53        52
       Tumor       0.66      0.78      0.72        69

    accuracy                           0.64       121
   macro avg       0.64      0.62      0.62       121
weighted avg       0.64      0.64      0.63       121


Unweighted Accuracy: 0.6446280991735537
Weighted Accuracy: 0.6220735785953178
4/4 [==============================] - 0s 87ms/step - loss: 401.6687 - binary_accuracy: 0.6446
