In [1]:
# MRI STUFF
# Test increase in layers 
# Increase in layer architectures
# Increase in drop out 
# With class weights, without class weights 

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow.keras.backend as K
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras import datasets, layers, models
from sklearn.metrics import (classification_report, confusion_matrix, balanced_accuracy_score, 
accuracy_score, roc_auc_score, auc)
from sklearn.model_selection import KFold, StratifiedKFold
import plotly.graph_objects as go
import glob


In [3]:
#drive.mount('/content/drive')

#ROOT_DIR = "/content/drive/MyDrive/Spring 2022/DTSC 870/Code" # HC Directory
#ROOT_DIR = "/content/drive/MyDrive/DTSC 870/Code" #MT Directory
KAGGLE_START = "/kaggle/input"
ROOT_DIR = KAGGLE_START
DATASET_01_TEST = KAGGLE_START + "/mri-test-set/test"
DATASET_01_TRAIN = KAGGLE_START + "/mri-trainset/train"
KAGGLE_OUT = "/kaggle/working"



In [4]:
datagen = ImageDataGenerator()
image_size = (256, 256)
test_set = datagen.flow_from_directory(DATASET_01_TEST, target_size=image_size, batch_size=32, class_mode='binary', shuffle=False)
train_set = datagen.flow_from_directory(DATASET_01_TRAIN, target_size=image_size, batch_size=32, class_mode='binary')


Found 121 images belonging to 2 classes.
Found 279 images belonging to 2 classes.


In [5]:
def create_model_V1():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(128, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model


In [6]:
def create_model_V1_02():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(128, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [7]:
def create_model_V1_04():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(128, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [8]:
def create_model_V2():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [9]:
def create_model_V2_02():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [10]:
def create_model_V2_04():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  #model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [11]:
def create_model_V3():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [12]:
def create_model_V3_02():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [13]:
def create_model_V3_04():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [14]:
def create_model_V4():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [15]:
def create_model_V4_02():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.2))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [16]:
def create_model_V4_04():
  model = models.Sequential()
  model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(256, 256, 3)))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  model.add(layers.Dropout(0.4))
  model.add(layers.Conv2D(128, (3, 3), activation='relu'))
  model.add(layers.MaxPooling2D((2, 2)))
  #model.add(layers.Conv2D(64, (3, 3), activation='relu'))
  model.add(layers.Conv2D(256, (3, 3), activation='relu'))
  model.add(layers.Flatten())
  model.add(layers.Dense(256, activation='relu'))
  model.add(layers.Dense(1, activation='sigmoid'))
  return model

In [17]:
#modify this 
norm_weight = 400/(2*(118+52))
tumor_weight = 400/(2*(161+69))

class_weights = {0:norm_weight, 1:tumor_weight}

In [18]:
import glob

#borrowed from svm code
def get_data_df(dir):
  # modified code from: https://www.kaggle.com/namgalielei/simple-load-images-and-count-number-of-each-class

  train_df = pd.DataFrame()

  trainset = glob.glob(dir)
  #print(trainset)
  train_df['filename'] = [img.split("/")[-4] + "/" + img.split("/")[-3] + "/" + img.split("/")[-2]+"/"+img.split("/")[-1] for img in trainset]
  train_df['label'] = [img.split("/")[-2] for img in trainset]

  return train_df

In [19]:
test_train = get_data_df(DATASET_01_TRAIN+"/*/*.jpg")
test_train.head()

filename  label
0   mri-trainset/train/Tumor/Tumor (77).jpg  Tumor
1  mri-trainset/train/Tumor/Tumor (116).jpg  Tumor
2   mri-trainset/train/Tumor/Tumor (86).jpg  Tumor
3   mri-trainset/train/Tumor/Tumor (49).jpg  Tumor
4   mri-trainset/train/Tumor/Tumor (40).jpg  Tumor

In [20]:
from sklearn.model_selection import KFold, StratifiedKFold

train_data = get_data_df(DATASET_01_TRAIN+"/*/*.jpg")
Y = train_data[['label']]

#Y = final_train[['label']]
#n = len(final_train)   

skf = StratifiedKFold(n_splits = 5, random_state = 7, shuffle = True) 

#Un needed preprocessing aside from rescale
idg = ImageDataGenerator(rescale=1./255)

#model name
def get_model_name(k):
    return 'model_'+str(k)+'.h5'
def model_test(fold_count, epoch, model_method, image_size):
  skf = StratifiedKFold(n_splits = fold_count, random_state = 7, shuffle = True)
  train_data = get_data_df(DATASET_01_TRAIN+"/*/*.jpg")
  Y = train_data[['label']]
  n = len (train_data)
  #Incorperate preprocessing in the method 
  #####################################################################
  #aug_train = get_data_df(DATASET_01_ROOT+"/Aug_train/*/*.jpg")
  #aug_train['filename'] = aug_train['filename'].str[7:]
  #final_train = test_train.append(aug_train, sort=False, ignore_index=True)


  #######################################################################
  idg = ImageDataGenerator(rescale=1./255)
  #idg = ImageDataGenerator()
  #Y = final_train[['label']]
  #n = len(final_train)    
  VALIDATION_ACCURACY = []
  VALIDATION_LOSS = []

  #create a directory
  save_dir = KAGGLE_OUT+'/datasets/01_MRI/Saved_CNN_Models/Testing/'+model_method.__name__+'/AugTest'+'/'+str(epoch)+'epochs/'
  img_dir = ROOT_DIR

  fold_var = 1

  #n is number of samples, doesn't care about x values for split, just y
  for train_index, val_index in skf.split(np.zeros(n),Y):

    #Index value for fold
    training_data = train_data.iloc[train_index]
    validation_data = train_data.iloc[val_index]
    #generator for train
    #print("hi")
    #Modify the training size, have an input adjustability 
    train_data_generator = idg.flow_from_dataframe(training_data, directory = img_dir,
                      target_size=image_size, batch_size=32,
                    x_col = "filename", y_col = "label",
                    class_mode = "binary", shuffle = True)
    #print("hi")
    #generator for validation
    valid_data_generator  = idg.flow_from_dataframe(validation_data, directory = img_dir,
                target_size=image_size, batch_size=32,
                x_col = "filename", y_col = "label",
                class_mode = "binary", shuffle = True)
    #print("hi")
    #create a method for this
    # CREATE NEW MODEL
    model = model_method()
    # COMPILE NEW MODEL
    #Binary cross entropy, opt will be adam, metric will be binary accuracy?
    model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
            optimizer= tf.keras.optimizers.Adam(),
            metrics=['binary_accuracy'])
    
    # CREATE CALLBACKS
    #Unsure about checpoint
    checkpoint = tf.keras.callbacks.ModelCheckpoint(save_dir+model_method.__name__+"_"+get_model_name(fold_var), 
                monitor='val_binary_accuracy', verbose=1, 
                save_best_only=True, mode='max')
  
    callbacks_list = [checkpoint]
    # There can be other callbacks, but just showing one because it involves the model name
    # This saves the best model
    # FIT THE MODEL
    #Include the weights for classes
    history = model.fit(train_data_generator,
            epochs=epoch,
            callbacks=callbacks_list,
            validation_data=valid_data_generator,
            class_weight = class_weights)
  
    #PLOT HISTORY
    #Plots for whichever
    #		:
    #plt.plot(history.history['binary_accuracy'], label='accuracy')
    #plt.plot(history.history['val_binary_accuracy'], label = 'val_accuracy')
    #plt.xlabel('Epoch')
    #plt.ylabel('Accuracy')
    #plt.ylim([0.3, 1])
    #plt.legend(loc='lower right')
    #plt.show()
    #frame = {'Accuracy': history.history['binary_accuracy'], 'Val_Accuracy': history.history['val_binary_accuracy']}
    #fig = px.line(frame)
    #fig.show()
    fig = go.Figure()
    fig.add_trace(go.Scatter(y= history.history['binary_accuracy'],
                      mode='lines+markers',
                      name='Training Accuracy'))
    fig.add_trace(go.Scatter(y= history.history['val_binary_accuracy'],
                      mode='lines+markers',
                      name='Validation Accuracy'))
    fig.update_yaxes(range=[0.40, 1])
    fig.update_layout(
      title="Fold "+ str(fold_var)+ "'s performance",
      title_x=0.5,
      xaxis_title="Epochs",
      yaxis_title="Accuracy",
      autosize=False,
      width=800,
      height=400,
      margin=dict(l=20, r=20, t=40, b=20),)
    fig.show()
    #		:
    # LOAD BEST MODEL to evaluate the performance of the model
    model.load_weights(save_dir+model_method.__name__+"_" + "model_"+str(fold_var)+".h5")
    predictions = model.predict(test_set)
    #predict_final = np.where(predictions >=0, 1,0)
    predict_final = K.round(predictions)
    conf_mat = confusion_matrix(test_set.classes, predict_final)
    conf_mat_perc = conf_mat.astype('float') / conf_mat.sum(axis=1)[:, np.newaxis]
    class_acc = conf_mat_perc.diagonal()
    print(conf_mat)
    print()
    print(f"Normal accuracy: {class_acc[0]}")
    print(f"Tumor accuracy: {class_acc[1]}")
    print()
    target_names = ['Normal', 'Tumor']
    print(classification_report(test_set.classes, predict_final, target_names=target_names))
    print()
    w_acc = balanced_accuracy_score(test_set.classes, predict_final) 
    u_acc = accuracy_score(test_set.classes, predict_final)
    print(f'Unweighted Accuracy: {u_acc}')  
    print(f'Weighted Accuracy: {w_acc}')
    results = model.evaluate(test_set)
    
    results = dict(zip(model.metrics_names,results))
    
    VALIDATION_ACCURACY.append(results['binary_accuracy'])
    VALIDATION_LOSS.append(results['loss'])
    
    tf.keras.backend.clear_session()
    
    fold_var += 1

In [21]:
#model_test(5, 30, create_model_V1, (256,256))

In [22]:
#model_test(5, 30, create_model_V1_02, (256,256))

In [23]:
#model_test(5, 30, create_model_V1_04, (256,256))

In [24]:
#model_test(5, 30, create_model_V2, (256,256))

In [25]:
#model_test(5, 30, create_model_V2_02, (256,256))

In [26]:
#model_test(5, 30, create_model_V2_04, (256,256))

In [27]:
#model_test(5, 30, create_model_V3, (256,256))

In [28]:
#model_test(5, 30, create_model_V3_02, (256,256))

In [29]:
#model_test(5, 30, create_model_V3_04, (256,256))

In [30]:
model_test(5, 30, create_model_V4, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.


2022-05-03 22:30:42.418591: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
2022-05-03 22:30:43.094351: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/30
7/7 [==============================] - 16s 2s/step - loss: 0.9305 - binary_accuracy: 0.4574 - val_loss: 0.6811 - val_binary_accuracy: 0.5893

Epoch 00001: val_binary_accuracy improved from -inf to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V4/AugTest/30epochs/create_model_V4_model_1.h5
Epoch 2/30
7/7 [==============================] - 14s 2s/step - loss: 0.7027 - binary_accuracy: 0.5785 - val_loss: 0.6923 - val_binary_accuracy: 0.7143

Epoch 00002: val_binary_accuracy improved from 0.58929 to 0.71429, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V4/AugTest/30epochs/create_model_V4_model_1.h5
Epoch 3/30
7/7 [==============================] - 13s 2s/step - loss: 0.6929 - binary_accuracy: 0.5874 - val_loss: 0.6897 - val_binary_accuracy: 0.6250

Epoch 00003: val_binary_accuracy did not improve from 0.71429
Epoch 4/30
7/7 [==============================] - 14s 2s/step - loss: 0.7016 - bin

[[40 12]
 [17 52]]

Normal accuracy: 0.7692307692307693
Tumor accuracy: 0.7536231884057971

              precision    recall  f1-score   support

      Normal       0.70      0.77      0.73        52
       Tumor       0.81      0.75      0.78        69

    accuracy                           0.76       121
   macro avg       0.76      0.76      0.76       121
weighted avg       0.76      0.76      0.76       121


Unweighted Accuracy: 0.7603305785123967
Weighted Accuracy: 0.7614269788182833
4/4 [==============================] - 2s 420ms/step - loss: 138.2700 - binary_accuracy: 0.7603
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 15s 2s/step - loss: 0.7731 - binary_accuracy: 0.4978 - val_loss: 0.6795 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[39 13]
 [ 9 60]]

Normal accuracy: 0.75
Tumor accuracy: 0.8695652173913043

              precision    recall  f1-score   support

      Normal       0.81      0.75      0.78        52
       Tumor       0.82      0.87      0.85        69

    accuracy                           0.82       121
   macro avg       0.82      0.81      0.81       121
weighted avg       0.82      0.82      0.82       121


Unweighted Accuracy: 0.8181818181818182
Weighted Accuracy: 0.8097826086956521
4/4 [==============================] - 2s 410ms/step - loss: 217.2628 - binary_accuracy: 0.8182
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 15s 2s/step - loss: 0.7855 - binary_accuracy: 0.5202 - val_loss: 0.6754 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_mode

[[33 19]
 [ 2 67]]

Normal accuracy: 0.6346153846153846
Tumor accuracy: 0.9710144927536232

              precision    recall  f1-score   support

      Normal       0.94      0.63      0.76        52
       Tumor       0.78      0.97      0.86        69

    accuracy                           0.83       121
   macro avg       0.86      0.80      0.81       121
weighted avg       0.85      0.83      0.82       121


Unweighted Accuracy: 0.8264462809917356
Weighted Accuracy: 0.8028149386845038
4/4 [==============================] - 2s 414ms/step - loss: 182.4462 - binary_accuracy: 0.8264
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 15s 2s/step - loss: 0.8605 - binary_accuracy: 0.4798 - val_loss: 0.6820 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[36 16]
 [11 58]]

Normal accuracy: 0.6923076923076923
Tumor accuracy: 0.8405797101449275

              precision    recall  f1-score   support

      Normal       0.77      0.69      0.73        52
       Tumor       0.78      0.84      0.81        69

    accuracy                           0.78       121
   macro avg       0.77      0.77      0.77       121
weighted avg       0.78      0.78      0.78       121


Unweighted Accuracy: 0.7768595041322314
Weighted Accuracy: 0.7664437012263099
4/4 [==============================] - 2s 417ms/step - loss: 158.1325 - binary_accuracy: 0.7769
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 15s 2s/step - loss: 0.9409 - binary_accuracy: 0.4375 - val_loss: 0.6974 - val_binary_accuracy: 0.4182

Epoch 00001: val_binary_accuracy improved from -inf to 0.41818, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[39 13]
 [16 53]]

Normal accuracy: 0.75
Tumor accuracy: 0.7681159420289855

              precision    recall  f1-score   support

      Normal       0.71      0.75      0.73        52
       Tumor       0.80      0.77      0.79        69

    accuracy                           0.76       121
   macro avg       0.76      0.76      0.76       121
weighted avg       0.76      0.76      0.76       121


Unweighted Accuracy: 0.7603305785123967
Weighted Accuracy: 0.7590579710144927
4/4 [==============================] - 2s 418ms/step - loss: 64.7812 - binary_accuracy: 0.7603


In [31]:
model_test(5, 30, create_model_V4_02, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 16s 2s/step - loss: 1.6617 - binary_accuracy: 0.5426 - val_loss: 0.6916 - val_binary_accuracy: 0.7321

Epoch 00001: val_binary_accuracy improved from -inf to 0.73214, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V4_02/AugTest/30epochs/create_model_V4_02_model_1.h5
Epoch 2/30
7/7 [==============================] - 15s 2s/step - loss: 0.6957 - binary_accuracy: 0.5067 - val_loss: 0.6909 - val_binary_accuracy: 0.5893

Epoch 00002: val_binary_accuracy did not improve from 0.73214
Epoch 3/30
7/7 [==============================] - 15s 2s/step - loss: 0.6920 - binary_accuracy: 0.5830 - val_loss: 0.6909 - val_binary_accuracy: 0.7500

Epoch 00003: val_binary_accuracy improved from 0.73214 to 0.75000, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V4_0

[[32 20]
 [ 8 61]]

Normal accuracy: 0.6153846153846154
Tumor accuracy: 0.8840579710144928

              precision    recall  f1-score   support

      Normal       0.80      0.62      0.70        52
       Tumor       0.75      0.88      0.81        69

    accuracy                           0.77       121
   macro avg       0.78      0.75      0.75       121
weighted avg       0.77      0.77      0.76       121


Unweighted Accuracy: 0.768595041322314
Weighted Accuracy: 0.749721293199554
4/4 [==============================] - 2s 428ms/step - loss: 291.6615 - binary_accuracy: 0.7686
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 16s 2s/step - loss: 1.2097 - binary_accuracy: 0.5516 - val_loss: 0.6862 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing

[[42 10]
 [13 56]]

Normal accuracy: 0.8076923076923077
Tumor accuracy: 0.8115942028985508

              precision    recall  f1-score   support

      Normal       0.76      0.81      0.79        52
       Tumor       0.85      0.81      0.83        69

    accuracy                           0.81       121
   macro avg       0.81      0.81      0.81       121
weighted avg       0.81      0.81      0.81       121


Unweighted Accuracy: 0.8099173553719008
Weighted Accuracy: 0.8096432552954292
4/4 [==============================] - 2s 419ms/step - loss: 186.4161 - binary_accuracy: 0.8099
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 16s 2s/step - loss: 1.2674 - binary_accuracy: 0.5695 - val_loss: 0.6943 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[31 21]
 [ 5 64]]

Normal accuracy: 0.5961538461538461
Tumor accuracy: 0.927536231884058

              precision    recall  f1-score   support

      Normal       0.86      0.60      0.70        52
       Tumor       0.75      0.93      0.83        69

    accuracy                           0.79       121
   macro avg       0.81      0.76      0.77       121
weighted avg       0.80      0.79      0.78       121


Unweighted Accuracy: 0.7851239669421488
Weighted Accuracy: 0.7618450390189521
4/4 [==============================] - 2s 430ms/step - loss: 229.3549 - binary_accuracy: 0.7851
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 16s 2s/step - loss: 2.4020 - binary_accuracy: 0.5336 - val_loss: 0.6895 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testin

[[45  7]
 [15 54]]

Normal accuracy: 0.8653846153846154
Tumor accuracy: 0.782608695652174

              precision    recall  f1-score   support

      Normal       0.75      0.87      0.80        52
       Tumor       0.89      0.78      0.83        69

    accuracy                           0.82       121
   macro avg       0.82      0.82      0.82       121
weighted avg       0.83      0.82      0.82       121


Unweighted Accuracy: 0.8181818181818182
Weighted Accuracy: 0.8239966555183946
4/4 [==============================] - 2s 422ms/step - loss: 146.2418 - binary_accuracy: 0.8182
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 17s 2s/step - loss: 0.7654 - binary_accuracy: 0.5268 - val_loss: 0.6755 - val_binary_accuracy: 0.5818

Epoch 00001: val_binary_accuracy improved from -inf to 0.58182, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testin

[[32 20]
 [11 58]]

Normal accuracy: 0.6153846153846154
Tumor accuracy: 0.8405797101449275

              precision    recall  f1-score   support

      Normal       0.74      0.62      0.67        52
       Tumor       0.74      0.84      0.79        69

    accuracy                           0.74       121
   macro avg       0.74      0.73      0.73       121
weighted avg       0.74      0.74      0.74       121


Unweighted Accuracy: 0.743801652892562
Weighted Accuracy: 0.7279821627647715
4/4 [==============================] - 2s 414ms/step - loss: 114.0359 - binary_accuracy: 0.7438


In [32]:
model_test(5, 30, create_model_V4_04, (256,256))

Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 16s 2s/step - loss: 1.2412 - binary_accuracy: 0.4709 - val_loss: 0.6919 - val_binary_accuracy: 0.5893

Epoch 00001: val_binary_accuracy improved from -inf to 0.58929, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V4_04/AugTest/30epochs/create_model_V4_04_model_1.h5
Epoch 2/30
7/7 [==============================] - 15s 2s/step - loss: 0.6927 - binary_accuracy: 0.5695 - val_loss: 0.6928 - val_binary_accuracy: 0.5893

Epoch 00002: val_binary_accuracy did not improve from 0.58929
Epoch 3/30
7/7 [==============================] - 15s 2s/step - loss: 0.6933 - binary_accuracy: 0.5740 - val_loss: 0.6921 - val_binary_accuracy: 0.7500

Epoch 00003: val_binary_accuracy improved from 0.58929 to 0.75000, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/create_model_V4_0

[[35 17]
 [12 57]]

Normal accuracy: 0.6730769230769231
Tumor accuracy: 0.8260869565217391

              precision    recall  f1-score   support

      Normal       0.74      0.67      0.71        52
       Tumor       0.77      0.83      0.80        69

    accuracy                           0.76       121
   macro avg       0.76      0.75      0.75       121
weighted avg       0.76      0.76      0.76       121


Unweighted Accuracy: 0.7603305785123967
Weighted Accuracy: 0.7495819397993311
4/4 [==============================] - 2s 405ms/step - loss: 114.8711 - binary_accuracy: 0.7603
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 17s 2s/step - loss: 1.4765 - binary_accuracy: 0.5067 - val_loss: 0.6929 - val_binary_accuracy: 0.6250

Epoch 00001: val_binary_accuracy improved from -inf to 0.62500, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[42 10]
 [10 59]]

Normal accuracy: 0.8076923076923077
Tumor accuracy: 0.855072463768116

              precision    recall  f1-score   support

      Normal       0.81      0.81      0.81        52
       Tumor       0.86      0.86      0.86        69

    accuracy                           0.83       121
   macro avg       0.83      0.83      0.83       121
weighted avg       0.83      0.83      0.83       121


Unweighted Accuracy: 0.8347107438016529
Weighted Accuracy: 0.8313823857302118
4/4 [==============================] - 2s 417ms/step - loss: 119.9540 - binary_accuracy: 0.8347
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 16s 2s/step - loss: 1.8914 - binary_accuracy: 0.5202 - val_loss: 0.6941 - val_binary_accuracy: 0.4286

Epoch 00001: val_binary_accuracy improved from -inf to 0.42857, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testin

[[37 15]
 [ 7 62]]

Normal accuracy: 0.7115384615384616
Tumor accuracy: 0.8985507246376812

              precision    recall  f1-score   support

      Normal       0.84      0.71      0.77        52
       Tumor       0.81      0.90      0.85        69

    accuracy                           0.82       121
   macro avg       0.82      0.81      0.81       121
weighted avg       0.82      0.82      0.82       121


Unweighted Accuracy: 0.8181818181818182
Weighted Accuracy: 0.8050445930880714
4/4 [==============================] - 2s 417ms/step - loss: 238.6847 - binary_accuracy: 0.8182
Found 223 validated image filenames belonging to 2 classes.
Found 56 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 16s 2s/step - loss: 1.3287 - binary_accuracy: 0.4753 - val_loss: 0.6921 - val_binary_accuracy: 0.5714

Epoch 00001: val_binary_accuracy improved from -inf to 0.57143, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testi

[[23 29]
 [ 5 64]]

Normal accuracy: 0.4423076923076923
Tumor accuracy: 0.927536231884058

              precision    recall  f1-score   support

      Normal       0.82      0.44      0.57        52
       Tumor       0.69      0.93      0.79        69

    accuracy                           0.72       121
   macro avg       0.75      0.68      0.68       121
weighted avg       0.75      0.72      0.70       121


Unweighted Accuracy: 0.71900826446281
Weighted Accuracy: 0.6849219620958751
4/4 [==============================] - 2s 417ms/step - loss: 230.6398 - binary_accuracy: 0.7190
Found 224 validated image filenames belonging to 2 classes.
Found 55 validated image filenames belonging to 2 classes.
Epoch 1/30
7/7 [==============================] - 17s 2s/step - loss: 1.5615 - binary_accuracy: 0.5000 - val_loss: 0.6940 - val_binary_accuracy: 0.4182

Epoch 00001: val_binary_accuracy improved from -inf to 0.41818, saving model to /kaggle/working/datasets/01_MRI/Saved_CNN_Models/Testing/

[[41 11]
 [11 58]]

Normal accuracy: 0.7884615384615384
Tumor accuracy: 0.8405797101449275

              precision    recall  f1-score   support

      Normal       0.79      0.79      0.79        52
       Tumor       0.84      0.84      0.84        69

    accuracy                           0.82       121
   macro avg       0.81      0.81      0.81       121
weighted avg       0.82      0.82      0.82       121


Unweighted Accuracy: 0.8181818181818182
Weighted Accuracy: 0.814520624303233
4/4 [==============================] - 2s 533ms/step - loss: 97.1105 - binary_accuracy: 0.8182
